
[tasks.build]
args = ["build", "--release"]
workspace = false

[tasks.cp]
script = '''
cp acts.conf  target/release/
'''
script_runner = "@shell"
workspace = false

[tasks.default]
# alias = "build"
clear = true
dependencies = [
  "build",
  "cp",
]
workspace = false
