[package]
edition = "2021"
name = "acts-grpc"
version = "0.1.0"

[dependencies]
prost = "0.11.8"
prost-types = "0.11.9"
serde = {version = "1.0.158", features = ["derive"]}
serde_json = "1.0.94"
tonic = "0.8.3"

[build-dependencies]
tonic-build = {version = "0.8.4"}
