# .github/workflows/release.yml

name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    name: build-release
    permissions:
      contents: write
    strategy:
      matrix:
        build: [linux-x86_64, macos-x86_64, windows-x86_64-gnu]
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: macos-x86_64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: windows-x86_64-gnu
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

        # Run build
      # - name: install rustup
      #   run: |
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
      #     sh rustup-init.sh -y --default-toolchain none
      #     rustup target add ${{ matrix.target }}

      - name: Setup msys2 toolchains
        if: matrix.rust == 'nightly-x86_64-gnu'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-gcc mingw-w64-i686-gcc

      - name: Prepare env for windows
        if: matrix.rust == 'nightly-x86_64-gnu'
        run: |
          # Add symlinks to the target-specific GNU sysroots for Clang
          New-Item -Path "C:\Program Files\LLVM\x86_64-w64-mingw32" -ItemType SymbolicLink -Value "C:\msys64\mingw64\x86_64-w64-mingw32"
          New-Item -Path "C:\Program Files\LLVM\i686-w64-mingw32" -ItemType SymbolicLink -Value "C:\msys64\mingw64\i686-w64-mingw32"
          # Add paths to GCC executables to PATH
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\msys64\mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # Configure CC_<target> environment variables
          echo "CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "CC_i686_pc_windows_gnu=i686-w64-mingw32-gcc" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          # echo "HOST_CC=x86_64-w64-mingw32-gcc" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
          components: rustfmt

      - name: build acts-server
        shell: bash
        run: |
          cargo clean
          cargo build --release --target ${{matrix.target}} --verbose

      - name: build acts-cli
        shell: bash
        run: |
          cargo clean
          cargo build --release --target ${{matrix.target}} -p acts-cli --verbose

      - name: Build archive
        shell: bash
        run: |
          staging="${{ matrix.build }}"
          mkdir -p "$staging"
          cp {README.md,LICENSE,acts.conf} "$staging/"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{matrix.target}}/release/acts-server.exe "$staging/"
            cp target/${{matrix.target}}/release/acts-cli.exe "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp target/${{matrix.target}}/release/acts-server "$staging/"
            cp target/${{matrix.target}}/release/acts-cli "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.ASSET }}
